name: Build and release Windows

# on:
#   push:
#     branches:
#       - main
on: workflow_dispatch


env:
  LLVM_VERSION: "15.0.6"
  FLUTTER_VERSION: "3.7.9"
  TAG_NAME: "nighly"

jobs:
  build-and-release-windows:
    name: Build Windows-x64
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        job: 
          - { target: x86_64-pc-windows-msvc, os: windows-latest, arch: x86_64 }
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ env.LLVM_VERSION }}
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - name: Install project dependencies
        run: flutter pub get
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.job.target }}
          override: true
          profile: minimal 
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.job.os }}
      - name: Install flutter rust bridge deps
        run: |
          cargo install flutter_rust_bridge_codegen
          flutter pub get
          ~/.cargo/bin/flutter_rust_bridge_codegen --rust-input native/src/api.rs --dart-output lib/bridge_generated.dart --dart-decl-output lib/bridge_definitions.dart
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable windows build
        run: flutter create --platforms=windows --project-name=git_act .
      - name: Build artifacts
        run: flutter build windows --release
      - name: copy dependencies
        run: |
          copy "assets\deps\windows\sqlite3.dll" "build\windows\runner\Release\sqlite3.dll"
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: Release-${{env.TAG_NAME}}-windows.zip
          directory: build/windows/runner/Release
      - name: Windows Release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          prerelease: true
          tag_name: ${{env.TAG_NAME}}
          files: build/windows/runner/Release/Release-${{env.TAG_NAME}}-windows.zip
