name: Build and release linux project

on:
  push:
    branches:
      - main

env:
  TAG_NAME: "nighly"

jobs:
  build-and-release-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          #flutter-version: '3.7.9'
      - run: flutter --version
      - name: Install dependencies
        run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable linux build
        run: flutter create --platforms=linux --project-name=google_exporter .
      - name: Build artifacts
        run: flutter build linux --release
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: GoogleExporter-${{env.TAG_NAME}}-linux.zip
          directory: build/linux/x64/release/bundle
      - name: Linux Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          prerelease: true
          tag_name: ${{env.TAG_NAME}}
          files: build/linux/x64/release/bundle/GoogleExporter-${{env.TAG_NAME}}-linux.zip
